### ISSUE TITLE
How would the gulp setup be if there were multiple views

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laracasts/Laravel-Elixir-Vueify-Setup#3]
@JeffreyWay, The starter kit gives a good example on the usage of Laravel Elixir and Vueify, Thank you very much, but would you be able to update the example for multiple views to see:
- how gulp file would look when multiple views need to use browserify.
- how the usage is on the blade files.
- how to create a custom filter with this setup

**Comment by matthijs110** [comment]
- If you mean: **How does the `gulpfile.js` look like when using multiple views?**: You can import the JS file in any view you want (or use [sections](https://laravel.com/docs/5.2/blade#template-inheritance)). When using multiple JavaScript files, just `browserify()` them all:

``` javascript
var elixir = require('laravel-elixir');
require('laravel-elixir-vueify');

elixir(function(mix) {
    mix.sass('app.scss');

    mix.browserify('app.js');
    mix.browserify('bundle.js');
    mix.browserify('otherstuff.js');
});
```
- Nothing is different when using views. Just import the compiled script (from the public folder) into the view as you are used to with 'vanilla' HTML. 
- The [Vue documentation](http://vuejs.org/guide/custom-filter.html) can tell and show you more about this. It is pretty easy. If you need more help: this [Laracast episode](https://laracasts.com/series/learning-vue-step-by-step/episodes/14) will show and explain more :)

Good luck 👍

**Comment by abishekrsrikaanth** [comment]
Hi @matthijs110 thanks for the info, I figured it out myself from the time I created this bug. Thanks for the info. Appreciate it.
