### ISSUE TITLE
TypeError: Elixir.ready is not a function

### ISSUE THREAD

**Issue by carterfort** [laracasts/Laravel-Elixir-Vueify-Setup#5]
This example doesn't appear to function any longer.

Error thrown: `TypeError: Elixir.ready is not a function`

Steps to reproduce:
1. `git clone https://github.com/laracasts/Laravel-Elixir-Vueify-Setup.git`
2. `cd Laravel-Elixir-Vueify-Setup/`
3. `composer install`
4. `npm install`
5. `gulp`

php -v 7.0.6
node -v 6.2.2
npm -v 3.9.5

**Comment by JeffreyWay** [comment]
Give it another try. There was a breaking commit yesterday that I've fixed.

**Comment by carterfort** [comment]
Confirmed functioning. Thanks, Jeffrey!

**Comment by murtaza-vhora** [comment]
Hi,

I have executed the following command and getting same error which is reported by @carterfort 
command : **npm install laravel-elixir-vueify --save-dev**

Error thrown: TypeError: Elixir.ready is not a function

please help me here what I need to do

**Comment by pasqualintosh** [comment]
Actually i solved with this:

package.json
`"laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue": "^0.1.4",
    "laravel-elixir-webpack-official": "^1.0.2",`

gulpfile.js 
`const elixir = require('laravel-elixir');

require('laravel-elixir-vue');elixir(mix => {

    mix.sass('app.scss').webpack('app.js');

    mix.scripts( [ 'app.js', ], 'public/js' );

});`
